margin = 120
always_for_in = true
remove_extra_newlines = true
whitespace_ops_in_indices = true
format_docstrings = true
trailing_comma = false
separate_kwargs_with_semicolon = true
disallow_single_arg_nesting = true